#
#  Import LIBRARIES
import random
import string

from fastapi import FastAPI, Request

#  Import FILES
#


app = FastAPI()


@app.middleware(middleware_type="http")
async def request_id_logging(request: Request, call_next):
    """call_next: A function that will receive the request as a parameter.
    This function will pass the request to the corresponding path operation.
    Then it returns the response generated by the corresponding path operation."""
    response = await call_next(request)
    random_letters: str = "".join(random.choice(seq=string.ascii_letters) for _ in range(10))
    print(f"Log {random_letters}")
    response.headers["X-Request-ID"] = random_letters
    return response


@app.get(path="/")
async def say_hi() -> str:
    return "Hello YouTube"
